@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type:  application/json

{
    "name": "teste 6",
    "email": "teste6@email.com",
    "password": "123456"
}


###

# @name authenticate

POST {{baseUrl}}/session
Content-Type: application/json

{
    "email": "teste3@email.com",
    "password":"123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MTEzNjIyMi01NjI2LTRmYTctODM1Yy01N2I3ZjFlOGE2MmYiLCJpYXQiOjE3NTk1MTI1NTgsImV4cCI6MTc1OTUxNjE1OH0.JE2dCnRSIvGDZfHe8CQFTWxafjIgdREg_45hUjfZkQFGO710gHqaMzoWIe0qapphW1oxt3KqNosEVUkD0RzKt48DZ57xUr_6YVUVRdesgTUUkvENhz6AKLMYYqC0mWX9SRXCrEPA3bnSAksx3IAd70wz1gUUDHY56BYV651MY3gD-ZfuuuWd0USzJ7fF9v1KMd8tzpWsAfvMWV9kQgOm5qAEyBh1Z5sGDJtVDMQLBDl7CQY900CpVvY1Mgn4ZLYh2MyaXeuEHqFiwnz17pKUDVu4_DcfV8WcnSS-2yED2l0AYGBAWhUnj8mD7o6RuSVFMSdYh8ETqjg4y4nbCRCcJQ

{
    "title":"cr7 tem quantos gols?",
    "content":"Faltam quantos gols para cristiano ronaldo alcançar os 1000?"
}