@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type:  application/json

{
    "name": "teste 6",
    "email": "teste6@email.com",
    "password": "123456"
}


###

# @name authenticate

POST {{baseUrl}}/session
Content-Type: application/json

{
    "email": "teste3@email.com",
    "password":"123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MTEzNjIyMi01NjI2LTRmYTctODM1Yy01N2I3ZjFlOGE2MmYiLCJpYXQiOjE3NTk1MDcyNjgsImV4cCI6MTc1OTUxMDg2OH0.LC0ZgPSYVflNF1CV1yqSsc1YDWUavfl1uKwVfemat1y4XG2_7fCWvPvhE5BYLAu_3VaVkkHv1sG3NZ0Lamt2ABzzMtvqwViTfXuNZu9QkttI8NTRtdCiXBiWB8PLTohrweo1YIru8gYg7vz8pV1J-kbqyL5RRlFTy9IEKF1eOnZIm8oxMYJn3f2QE3AQWy6HGwIHjHtwJ0eXGqYxlULX7apyxzKqPkJUsEIJgBJ9zKVdQyunIujP1yLK3WLQxncNXXpt3q7zuZGy8RCp9rjsfVPl6TOzwsNOQbIhJM4fwcyV0SaPiOaSE1WMEm-FeglFM79l2iWCsb4INk7Tl7cv_g
